export let quests = [
  {
    title: "./flags/af.png",
    alts: ["Afeganistão", "Síria", "Arábia Saudita", "Nigéria", "Turquia"],
    correct: 0,
    lvl: 1,
  },
  {
    title: "./flags/za.png",
    alts: ["México", "Paquistão", "Egito", "África do Sul", "Panamá"],
    correct: 3,
    lvl: 1,
  },
  {
    title: "./flags/al.png",
    alts: ["Israel", "Albânia", "Espanha", "Suíça", "Polônia"],
    correct: 1,
    lvl: 1,
  },
  {
    title: "./flags/de.png",
    alts: ["Noruega", "Montenegro", "Japão", "Colômbia", "Alemanha"],
    correct: 4,
    lvl: 1,
  },
  {
    title: "./flags/ad.png",
    alts: ["Dominica", "Eritreia", "Andorra", "Djibouti", "Eslovênia"],
    correct: 2,
    lvl: 2,
  },
  {
    title: "./flags/ao.png",
    alts: ["Gabão", "Angola", "Kosovo", "Gana", "Jordânia"],
    correct: 1,
    lvl: 1,
  },
  {
    title: "./flags/ai.png",
    alts: [
      "Países Baixos Caribenhos",
      "Líbia",
      "Polinésia Francesa",
      "Porto Rico",
      "Anguila",
    ],
    correct: 4,
    lvl: 3,
  },
  {
    title: "./flags/aq.png",
    alts: [
      "Antártica",
      "Ilhas Marshall",
      "Porto Rico",
      "Líbano",
      "Ilhas Åland",
    ],
    correct: 0,
    lvl: 3,
  },
  {
    title: "./flags/ag.png",
    alts: [
      "Antígua e Barbuda",
      "Ilhas Åland",
      "Guernsey",
      "Hong Kong",
      "Micronésia",
    ],
    correct: 0,
    lvl: 2,
  },
  {
    title: "./flags/sa.png",
    alts: ["Irã", "França", "Gabão", "Arábia Saudita", "Indonésia"],
    correct: 3,
    lvl: 1,
  },
  {
    title: "./flags/dz.png",
    alts: ["Argélia", "Japão", "Jamaica", "Marrocos", "Paquistão"],
    correct: 0,
    lvl: 1,
  },
  {
    title: "./flags/ar.png",
    alts: ["Argentina", "Islândia", "Armênia", "Argélia", "Irlanda"],
    correct: 0,
    lvl: 1,
  },
  {
    title: "./flags/am.png",
    alts: ["Austrália", "China", "Cuba", "Honduras", "Armênia"],
    correct: 4,
    lvl: 1,
  },
  {
    title: "./flags/aw.png",
    alts: ["Aruba", "Guernsey", "Curaçao", "Ilhas Cook", "Ilhas Malvinas"],
    correct: 0,
    lvl: 3,
  },
  {
    title: "./flags/au.png",
    alts: ["Irã", "Austrália", "Índia", "Luxemburgo	", "Nova Zelândia"],
    correct: 1,
    lvl: 1,
  },
  {
    title: "./flags/at.png",
    alts: ["Eslováquia", "Nova Zelândia", "Nicarágua", "Áustria", "Panamá"],
    correct: 3,
    lvl: 1,
  },
  {
    title: "./flags/az.png",
    alts: ["Djibouti", "Fiji", "Azerbaijão", "Paquistão", "Dominica"],
    correct: 2,
    lvl: 2,
  },
  {
    title: "./flags/bs.png",
    alts: ["Quênia", "Quirguizistão", "Bahamas", "Paquistão", "Zimbábue"],
    correct: 2,
    lvl: 2,
  },
  {
    title: "./flags/bh.png",
    alts: ["Zimbábue", "Sri Lanka", "Tonga", "Bahrein", "Vanuatu"],
    correct: 3,
    lvl: 2,
  },
  {
    title: "./flags/bd.png",
    alts: ["Síria", "Tonga", "Timor Leste", "Somália", "Bangladesh"],
    correct: 4,
    lvl: 2,
  },
  {
    title: "./flags/bb.png",
    alts: [
      "Barbados",
      "República Centro-Africana",
      "Seychelles",
      "Suíça",
      "Timor Leste",
    ],
    correct: 0,
    lvl: 2,
  },
  {
    title: "./flags/by.png",
    alts: ["Palestina", "Belarus", "Palau", "Mali", "Qatar"],
    correct: 1,
    lvl: 1,
  },
  {
    title: "./flags/be.png",
    alts: ["Estônia", "Nigéria", "México", "Bélgica", "Chile"],
    correct: 3,
    lvl: 1,
  },
  {
    title: "./flags/bz.png",
    alts: ["Belize", "Coréia do Norte", "Costa Rica", "Islândia", "Japão"],
    correct: 0,
    lvl: 1,
  },
  {
    title: "./flags/bj.png",
    alts: ["Kosovo", "Mongólia", "Kiribati", "Jordânia", "Benin"],
    correct: 4,
    lvl: 2,
  },
  {
    title: "./flags/bm.png",
    alts: ["Norte da Macedônia", "Bermudas", "Namíbia", "Mongólia", "Palau"],
    correct: 1,
    lvl: 3,
  },
  {
    title: "./flags/bo.png",
    alts: [
      "Papua Nova Guiné",
      "República Dominicana",
      "Bolívia",
      "São Marino",
      "Quênia",
    ],
    correct: 2,
    lvl: 1,
  },
  {
    title: "./flags/ba.png",
    alts: ["Senegal", "Uruguai", "Vietnã", "Bósnia e Herzegovina	", "Suíça"],
    correct: 3,
    lvl: 1,
  },
  {
    title: "./flags/bw.png",
    alts: ["Zâmbia", "Tunísia", "Tanzânia", "Botsuana", "Serra Leoa"],
    correct: 3,
    lvl: 2,
  },
  {
    title: "./flags/br.png",
    alts: ["Romênia", "Brasil", "Rússia", "Nigéria", "Luxemburgo"],
    correct: 1,
    lvl: 1,
  },
  {
    title: "./flags/bn.png",
    alts: ["Malauí", "Liechtenstein", "Omã", "Brunei", "Líbia"],
    correct: 3,
    lvl: 2,
  },
  {
    title: "./flags/bg.png",
    alts: [
      "Bulgária",
      "Países Baixos	",
      "Antígua e Barbuda",
      "Panamá",
      "Arábia Saudita",
    ],
    correct: 0,
    lvl: 1,
  },
  {
    title: "./flags/bf.png",
    alts: ["Aruba", "Etiópia", "Antígua e Barbuda", "Burkina Faso", "Cuba"],
    correct: 3,
    lvl: 2,
  },
  {
    title: "./flags/bi.png",
    alts: ["Filipinas", "Haiti", "Zâmbia", "Fiji", "Burundi"],
    correct: 4,
    lvl: 2,
  },
  {
    title: "./flags/bt.png",
    alts: ["Venezuela", "Butão", "Vietnã", "Dinamarca", "Gana"],
    correct: 1,
    lvl: 1,
  },
  {
    title: "./flags/cv.png",
    alts: ["Djibouti", "Cabo Verde", "Zimbábue", "Vanuatu", "Grenada"],
    lvl: 2,
    correct: 1,
  },
  {
    title: "./flags/cm.png",
    alts: ["Camarões", "Haiti", "Jamaica", "Gana", "Colômbia"],
    correct: 0,
    lvl: 1,
  },
  {
    title: "./flags/kh.png",
    alts: ["Coréia do Norte", "Grécia", "Guatemala", "Croácia", "Camboja"],
    correct: 4,
    lvl: 1,
  },
  {
    title: "./flags/ca.png",
    alts: ["Canadá", "Finlândia", "Equador", "Dinamarca", "Chile"],
    correct: 0,
    lvl: 1,
  },
  {
    title: "./flags/kz.png",
    alts: ["Camboja", "Chipre", "Cazaquistão", "Finlândia", "Gana"],
    correct: 2,
    lvl: 1,
  },
  {
    title: "./flags/td.png",
    alts: ["Fiji", "Mali", "República do Congo", "Chade", "Eswatini"],
    correct: 3,
    lvl: 2,
  },
  {
    title: "./flags/cl.png",
    alts: ["Romênia", "Hong Kong", "Vietnã", "Rússia", "Chile"],
    correct: 4,
    lvl: 1,
  },
  {
    title: "./flags/cn.png",
    alts: ["Hungria", "Indonésia", "Irlanda", "China", "Hong Kong"],
    correct: 3,
    lvl: 1,
  },
  {
    title: "./flags/cy.png",
    alts: ["Jamaica", "Chipre", "Líbano", "Noruega", "Marrocos"],
    correct: 1,
    lvl: 1,
  },
  {
    title: "./flags/va.png",
    alts: [
      "Quirguizistão	",
      "República Democrática do Congo",
      "Síria",
      "Cidade do Vaticano",
      "República Centro-Africana",
    ],
    correct: 3,
    lvl: 2,
  },
  {
    title: "./flags/sg.png",
    alts: [
      "Singapura",
      "Namíbia",
      "Montenegro",
      "Polônia",
      "Norte da Macedônia",
    ],
    correct: 0,
    lvl: 2,
  },
  {
    title: "./flags/co.png",
    alts: ["Suécia", "Senegal", "Colômbia", "Peru", "Uruguai"],
    correct: 2,
    lvl: 1,
  },
  {
    title: "./flags/km.png",
    alts: ["Comores", "Tuvalu", "Vanuatu", "Zimbábue", "Trinidad e Tobago"],
    correct: 0,
    lvl: 2,
  },
  {
    title: "./flags/kp.png",
    alts: ["Nicarágua", "Portugal", "Tcheca", "Coréia do Norte", "Índia"],
    correct: 3,
    lvl: 1,
  },
  {
    title: "./flags/kr.png",
    alts: ["Lesotho", "Paquistão	", "Coréia do Sul", "Índia", "Letônia"],
    correct: 2,
    lvl: 1,
  },
  {
    title: "./flags/ci.png",
    alts: ["Gana", "Costa do Marfim", "Panamá", "Equador", "Irlanda"],
    correct: 1,
    lvl: 1,
  },
  {
    title: "./flags/cr.png",
    alts: ["Sérvia", "Islândia", "Israel", "Costa Rica", "Venezuela"],
    correct: 3,
    lvl: 1,
  },
  {
    title: "./flags/hr.png",
    alts: ["Ucrânia", "Croácia", "Martinica	", "Haiti", "Estônia"],
    correct: 1,
    lvl: 1,
  },
  {
    title: "./flags/cu.png",
    alts: ["Colômbia", "Belize", "Coréia do Norte", "Filipinas", "Cuba"],
    correct: 4,
    lvl: 1,
  },
  {
    title: "./flags/cw.png",
    alts: [
      "Guam",
      "Curaçao",
      "Ilhas Cook",
      "Ilhas Virgens dos Estados Unidos",
      "Ilha de Natal",
    ],
    correct: 1,
    lvl: 3,
  },
  {
    title: "./flags/dk.png",
    alts: ["Dinamarca", "Jamaica", "Luxemburgo", "Itália", "Portugal"],
    correct: 0,
    lvl: 1,
  },
  {
    title: "./flags/dj.png",
    alts: [
      "Papua Nova Guiné",
      "Djibouti",
      "Ruanda",
      "República do Congo",
      "São Marino",
    ],
    correct: 1,
    lvl: 2,
  },
  {
    title: "./flags/dm.png",
    alts: [
      "São Vicente e as Granadinas",
      "Tanzânia",
      "Dominica",
      "Togo",
      "Uzbequistão",
    ],
    correct: 2,
    lvl: 2,
  },
  {
    title: "./flags/eg.png",
    alts: ["Uganda", "Lesotho", "Egito", "Gana", "Ucrânia"],
    correct: 2,
    lvl: 1,
  },
  {
    title: "./flags/sv.png",
    alts: ["México", "Filipinas", "Etiópia", "El Salvador", "Nicarágua"],
    correct: 3,
    lvl: 1,
  },
  {
    title: "./flags/ae.png",
    alts: [
      "Emirados Árabes Unidos	",
      "Mongólia",
      "Namíbia",
      "Omã",
      "República do Congo",
    ],
    correct: 0,
    lvl: 2,
  },
  {
    title: "./flags/ec.png",
    alts: ["Uruguai", "Tcheca", "Rússia", "Senegal", "Equador"],
    correct: 4,
    lvl: 1,
  },
  {
    title: "./flags/er.png",
    alts: ["Uzbequistão", "Tajiquistão", "Eritreia", "Zâmbia", "Sudão do Sul	"],
    correct: 2,
    lvl: 2,
  },
  {
    title: "./flags/sk.png",
    alts: ["Eslováquia", "Suécia", "Romênia", "Índia", "Angola"],
    correct: 0,
    lvl: 1,
  },
  {
    title: "./flags/si.png",
    alts: ["Estônia", "Guatemala", "Jamaica", "Eslovênia", "Espanha"],
    correct: 3,
    lvl: 1,
  },
  {
    title: "./flags/es.png",
    alts: ["Japão", "Espanha", "Letônia", "Nigéria", "Turquia"],
    correct: 1,
    lvl: 1,
  },
  {
    title: "./flags/fm.png",
    alts: [
      "Tuvalu",
      "Turcomenistão	",
      "Sudão",
      "Estados Federados da Micronésia",
      "St. Kitts e Nevis",
    ],
    correct: 3,
    lvl: 2,
  },
  {
    title: "./flags/us.png",
    alts: [
      "Nova Zelândia	",
      "Israel",
      "Grécia",
      "Suíça",
      "Estados Unidos da América",
    ],
    correct: 4,
    lvl: 1,
  },
  {
    title: "./flags/ee.png",
    alts: ["Gabão", "Serra Leoa	", "Estônia", "Trinidad e Tobago", "Gâmbia"],
    correct: 2,
    lvl: 2,
  },
  {
    title: "./flags/sz.png",
    alts: ["Somália", "Eswatini", "Timor Leste", "Quênia", "Nauru"],
    correct: 1,
    lvl: 2,
  },
  {
    title: "./flags/et.png",
    alts: ["Nepal", "Mongólia", "Ilhas Marshall	", "Líbia", "Etiópia"],
    correct: 4,
    lvl: 2,
  },
  {
    title: "./flags/fj.png",
    alts: [
      "Liechtenstein	",
      "Tuvalu",
      "Fiji",
      "Seychelles",
      "República Democrática do Congo",
    ],
    correct: 2,
    lvl: 2,
  },
  {
    title: "./flags/ph.png",
    alts: ["Filipinas", "Irlanda", "Polônia", "Lituânia", "Indonésia"],
    correct: 0,
    lvl: 2,
  },
  {
    title: "./flags/fi.png",
    alts: ["Islândia", "Noruega", "Países Baixos", "Peru", "Finlândia"],
    correct: 4,
    lvl: 1,
  },
  {
    title: "./flags/fr.png",
    alts: ["Panamá", "França", "Alemanha", "Espanha", "Portugal"],
    correct: 1,
    lvl: 1,
  },
  {
    title: "./flags/ga.png",
    alts: ["Estônia", "Grenada", "Tanzânia", "Gabão", "Etiópia"],
    correct: 3,
    lvl: 2,
  },
  {
    title: "./flags/gm.png",
    alts: ["Guiana", "Gâmbia", "Taiwan", "Maurício", "Sudão do Sul	"],
    correct: 1,
    lvl: 2,
  },
  {
    title: "./flags/gh.png",
    alts: ["Gana", "Norte da Macedônia", "Qatar", "Senegal", "México"],
    correct: 0,
    lvl: 1,
  },
  {
    title: "./flags/ge.png",
    alts: [
      "São Pedro e Miquelon",
      "Ilhas Faroe",
      "Ilhas Åland	",
      "Wallis e Futuna",
      "Geórgia",
    ],
    correct: 4,
    lvl: 3,
  },
  {
    title: "./flags/gs.png",
    alts: [
      "Ilhas Åland	",
      "Ilha de Man",
      "Bermudas",
      "Geórgia do Sul e as Ilhas Sandwich do Sul",
      "Ilha Norfolk",
      "Anguila",
    ],
    correct: 3,
    lvl: 3,
  },
  {
    title: "./flags/gi.png",
    alts: [
      "Geórgia do Sul e as Ilhas Sandwich do Sul",
      "Ilhas Cocos",
      "Macau",
      "Gibraltar",
      "Ilhas Turcas e Caicos",
    ],
    correct: 3,
    lvl: 3,
  },
  {
    title: "./flags/gr.png",
    alts: ["Grécia", "Letônia", "Suíça", "Vietnã", "Portugal"],
    correct: 0,
    lvl: 1,
  },
  {
    title: "./flags/gd.png",
    alts: ["Tanzânia", "Grenada", "São Marino", "Quirguizistão	", "Fiji"],
    correct: 1,
    lvl: 2,
  },
  {
    title: "./flags/gl.png",
    alts: ["Etiópia", "Brunei", "Gronelândia", "Togo", "Burundi"],
    correct: 2,
    lvl: 2,
  },
  {
    title: "./flags/gp.png",
    alts: [
      "Wallis e Futuna",
      "Guam",
      "Ilhas Virgens (Reino Unido)",
      "Tokelau",
      "Guadalupe",
    ],
    correct: 4,
    lvl: 3,
  },
  {
    title: "./flags/gu.png",
    alts: [
      "Guam",
      "Ilhas Virgens dos Estados Unidos",
      "Ilha da Reunião",
      "Guernsey",
      "Ilha de Man",
    ],
    correct: 0,
    lvl: 3,
  },
  {
    title: "./flags/gt.png",
    alts: ["Haiti", "Brasil", "Áustria", "Guatemala", "Honduras	"],
    correct: 3,
    lvl: 1,
  },
  {
    title: "./flags/gg.png",
    alts: ["Jersey", "Guernsey", "Mayotte", "Niue", "Ilha de Man"],
    correct: 1,
    lvl: 3,
  },
  {
    title: "./flags/gy.png",
    alts: ["Indonésia", "Mali", "Guiana", "Malauí", "Norte da Macedônia"],
    correct: 2,
    lvl: 2,
  },
  {
    title: "./flags/gf.png",
    alts: [
      "Niue",
      "Samoa Americana",
      "Nova Caledônia	",
      "Guiana Francesa",
      "Ilhas Faroe",
    ],
    correct: 3,
    lvl: 3,
  },
  {
    title: "./flags/gn.png",
    alts: ["Ruanda", "Guiné", "Iraque", "Líbia", "Madagascar"],
    correct: 1,
    lvl: 2,
  },
  {
    title: "./flags/gq.png",
    alts: ["Serra Leoa	", "Seychelles", "Togo", "Vanuatu", "Guiné Equatorial"],
    correct: 4,
    lvl: 2,
  },
  {
    title: "./flags/gw.png",
    alts: [
      "Guiné-Bissau",
      "Tuvalu",
      "Palestina",
      "Nepal",
      "Emirados Árabes Unidos	",
    ],
    correct: 0,
    lvl: 2,
  },
  {
    title: "./flags/ht.png",
    alts: ["Equador", "Eslováquia", "Afeganistão", "Belize", "Haiti"],
    correct: 4,
    lvl: 1,
  },

  {
    title: "./flags/hn.png",
    alts: ["Bolívia", "Honduras	", "Canadá", "Costa do Marfim", "Romênia"],
    correct: 1,
    lvl: 1,
  },
  {
    title: "./flags/hk.png",
    alts: [
      "Zâmbia",
      "Timor Leste	",
      "Hong Kong",
      "República Democrática do Congo",
      "Libéria",
    ],
    correct: 2,
    lvl: 2,
  },
  {
    title: "./flags/hu.png",
    alts: ["Kosovo", "Lituânia", "Hungria", "Indonésia", "Gabão"],
    correct: 2,
    lvl: 1,
  },
  {
    title: "./flags/ye.png",
    alts: ["Iêmen", "Grenada", "Bahamas", "Namíbia", "Brunei"],
    correct: 0,
    lvl: 2,
  },
  {
    title: "./flags/re.png",
    alts: [
      "Ilha de Natal",
      "Jersey",
      "Ilha da Reunião",
      "Ilha de Man",
      "Polinésia Francesa",
    ],
    correct: 2,
    lvl: 3,
  },
  {
    title: "./flags/im.png",
    alts: [
      "Santa Helena",
      "São Pedro e Miquelon",
      "Ilhas Malvinas	",
      "Ilha de Man",
      "Ilhas Åland",
    ],
    correct: 3,
    lvl: 3,
  },
  {
    title: "./flags/cx.png",
    alts: [
      "Ilha de Natal	",
      "Guam",
      "Ilhas Marianas do Norte",
      "Antártica",
      "Ilha da Reunião",
    ],
    correct: 0,
    lvl: 3,
  },
  {
    title: "./flags/nf.png",
    alts: [
      "Anguila",
      "Ilha Norfolk",
      "Gronelândia	",
      "Ilha de Man",
      "Montserrat	",
    ],
    correct: 1,
    lvl: 3,
  },
  {
    title: "./flags/ax.png",
    alts: [
      "Samoa",
      "Países Baixos Caribenhos",
      "Niue",
      "Montserrat	",
      "Ilhas Åland",
    ],
    correct: 4,
    lvl: 3,
  },
  {
    title: "./flags/ky.png",
    alts: [
      "Niue",
      "Polinésia Francesa",
      "Países Baixos Caribenhos",
      "Samoa Americana",
      "Ilhas Cayman	",
    ],
    correct: 4,
    lvl: 3,
  },
  {
    title: "./flags/cc.png",
    alts: [
      "Samoa",
      "Samoa Americana",
      "Sint Maarten",
      "Ilhas Cocos",
      "Território Britânico do Oceano Índico	",
    ],
    correct: 3,
    lvl: 3,
  },
  {
    title: "./flags/ck.png",
    alts: [
      "Território Britânico do Oceano Índico	",
      "São Pedro e Miquelon",
      "Ilhas Cook",
      "Nova Caledônia",
      "Tokelau",
    ],
    correct: 2,
    lvl: 3,
  },
  {
    title: "./flags/fo.png",
    alts: [
      "Território Britânico do Oceano Índico	",
      "Wallis e Futuna",
      "Ilhas Faroe",
      "Nova Caledônia",
      "Tokelau",
    ],
    correct: 2,
    lvl: 3,
  },
  {
    title: "./flags/fk.png",
    alts: [
      "Ilhas Malvinas	",
      "Geórgia",
      "Ilhas Åland",
      "Ilhas Cocos	",
      "Guernsey",
    ],
    correct: 0,
    lvl: 3,
  },
  {
    title: "./flags/mp.png",
    alts: [
      "Ilhas Marianas do Norte",
      "Gibraltar",
      "Ilhas Malvinas	",
      "Ilhas Cook",
      "Ilhas Turcas e Caicos",
    ],
    correct: 0,
    lvl: 3,
  },
  {
    title: "./flags/mh.png",
    alts: ["Jordânia", "Kosovo", "Maldivas", "Ilhas Marshall	", "Kiribati"],
    correct: 3,
    lvl: 2,
  },
  {
    title: "./flags/pn.png",
    alts: [
      "Ilhas Marianas do Norte",
      "Guam",
      "Curaçao",
      "Ilhas Pitcairn	",
      "Ilhas Cook",
    ],
    correct: 3,
    lvl: 3,
  },
  {
    title: "./flags/sb.png",
    alts: ["Curaçao", "Ilhas Salomão", "Guernsey", "Ilha Norfolk	", "Jersey"],
    correct: 1,
    lvl: 2,
  },
  {
    title: "./flags/tc.png",
    alts: [
      "Wallis e Futuna",
      "Ilhas Turcas e Caicos",
      "Polinésia Francesa",
      "Jersey",
      "Ilhas Virgens (Reino Unido)",
    ],
    correct: 1,
    lvl: 3,
  },
  {
    title: "./flags/vg.png",
    alts: [
      "Ilhas Cocos",
      "Ilhas Virgens dos Estados Unidos",
      "Ilhas Virgens (Reino Unido)",
      "Territórios Franceses do Sul e Antártico",
      "Samoa",
    ],
    correct: 2,
    lvl: 3,
  },
  {
    title: "./flags/vi.png",
    alts: [
      "Wallis e Futuna",
      "Ilhas Virgens dos Estados Unidos",
      "Samoa",
      "Ilhas Malvinas	",
      "Gibraltar",
    ],
    correct: 1,
    lvl: 3,
  },
  {
    title: "./flags/in.png",
    alts: ["Estônia", "Grécia", "Guatemala", "Luxemburgo", "Índia"],
    correct: 4,
    lvl: 1,
  },
  {
    title: "./flags/id.png",
    alts: ["Mauritânia", "Indonésia", "Maurício", "Letônia", "Luxemburgo"],
    correct: 1,
    lvl: 2,
  },
  {
    title: "./flags/ir.png",
    alts: ["México", "Irã", "Nigéria", "Romênia", "Tcheca"],
    correct: 1,
    lvl: 1,
  },
  {
    title: "./flags/iq.png",
    alts: ["Tcheca", "Vietnã", "Venezuela", "Uruguai", "Iraque"],
    correct: 4,
    lvl: 1,
  },
  {
    title: "./flags/ie.png",
    alts: ["Costa do Marfim", "Reino Unido", "Irlanda", "Uruguai", "Qatar"],
    correct: 2,
    lvl: 1,
  },
  {
    title: "./flags/is.png",
    alts: ["Canadá", "Dinamarca", "Croácia", "Islândia", "Albânia"],
    correct: 3,
    lvl: 1,
  },
  {
    title: "./flags/il.png",
    alts: ["Brasil", "Israel", "Chile", "Japão", "Albânia"],
    correct: 1,
    lvl: 1,
  },
  {
    title: "./flags/it.png",
    alts: ["Finlândia", "México", "Jamaica", "Itália", "França"],
    correct: 3,
    lvl: 1,
  },
  {
    title: "./flags/jm.png",
    alts: ["Jamaica", "Filipinas", "Irlanda", "Letônia	", "Kosovo"],
    correct: 0,
    lvl: 1,
  },
  {
    title: "./flags/jp.png",
    alts: ["Japão", "Kosovo", "Rússia", "Palau", "Panamá"],
    correct: 0,
    lvl: 1,
  },
  {
    title: "./flags/je.png",
    alts: [
      "Sint Maarten",
      "Jersey",
      "Samoa Americana",
      "Ilhas Faroe",
      "Ilhas Åland",
    ],
    correct: 1,
    lvl: 3,
  },
  {
    title: "./flags/jo.png",
    alts: [
      "Iraque",
      "Moçambique	",
      "Jordânia",
      "República Democrática do Congo",
      "Namíbia",
    ],
    correct: 2,
    lvl: 2,
  },
  {
    title: "./flags/ki.png",
    alts: [
      "República Centro-Africana",
      "Quirguizistão",
      "São Tomé e Príncipe",
      "Sudão do Sul",
      "Kiribati",
    ],
    correct: 4,
    lvl: 2,
  },
  {
    title: "./flags/xk.png",
    alts: ["Suécia", "Suíça", "Kosovo", "Turquia", "Letônia"],
    correct: 2,
    lvl: 1,
  },
  {
    title: "./flags/kw.png",
    alts: ["Kiribati", "Mali", "Grenada", "Djibouti", "Kuwait"],
    correct: 4,
    lvl: 2,
  },
  {
    title: "./flags/la.png",
    alts: ["Laos", "Kiribati", "Maldivas", "Filipinas", "Dominica"],
    correct: 0,
    lvl: 2,
  },
  {
    title: "./flags/ls.png",
    alts: ["Eritreia", "Gabão", "Gâmbia", "mirados Árabes Unidos", "Lesotho"],
    correct: 4,
    lvl: 2,
  },
  {
    title: "./flags/lv.png",
    alts: ["Finlândia", "Estônia", "Hungria", "Panamá", "Letônia"],
    correct: 4,
    lvl: 1,
  },
  {
    title: "./flags/lb.png",
    alts: ["Reino Unido", "Líbano", "Qatar", "Senegal", "Suíça"],
    correct: 1,
    lvl: 1,
  },
  {
    title: "./flags/lr.png",
    alts: ["Suriname", "Sri Lanka", "Libéria", "Uganda", "Uzbequistão"],
    correct: 2,
    lvl: 2,
  },
  {
    title: "./flags/ly.png",
    alts: [
      "St. Kitts e Nevis",
      "Síria",
      "Trinidad e Tobago",
      "Vanuatu",
      "Líbia",
    ],
    correct: 4,
    lvl: 2,
  },
  {
    title: "./flags/li.png",
    alts: ["Vanuatu", "Turcomenistão	", "Tonga", "Liechtenstein", "Togo"],
    correct: 3,
    lvl: 2,
  },
  {
    title: "./flags/lt.png",
    alts: ["Uruguai", "África do Sul", "Lituânia", "Angola", "Bulgária"],
    correct: 2,
    lvl: 1,
  },
  {
    title: "./flags/lu.png",
    alts: ["Chipre	", "Colômbia", "Bulgária", "Luxemburgo", "Camboja"],
    correct: 3,
    lvl: 1,
  },
  {
    title: "./flags/mo.png",
    alts: [
      "Tokelau",
      "Sint Maarten	",
      "Ilhas Virgens dos Estados Unidos",
      "Território Britânico do Oceano Índico	",
      "Macau",
    ],
    correct: 4,
    lvl: 3,
  },
  {
    title: "./flags/mg.png",
    alts: ["Timor Leste", "Madagascar", "Togo", "Benin", "Barbados"],
    correct: 1,
    lvl: 2,
  },
  {
    title: "./flags/my.png",
    alts: ["Malásia", "Belize", "Camboja", "Malauí", "Barbados"],
    correct: 0,
    lvl: 2,
  },
  {
    title: "./flags/mw.png",
    alts: ["Malauí", "Maldivas", "Malásia", "Maurício", "Grenada"],
    correct: 0,
    lvl: 2,
  },
  {
    title: "./flags/mv.png",
    alts: ["Gâmbia", "Cabo Verde	", "Grenada", "Maldivas", "Azerbaijão"],
    correct: 3,
    lvl: 2,
  },
  {
    title: "./flags/ml.png",
    alts: ["Burkina Faso	", "Níger", "Mali", "Cabo Verde	", "Palestina"],
    correct: 2,
    lvl: 2,
  },
  {
    title: "./flags/mt.png",
    alts: [
      "Malta",
      "Papua Nova Guiné",
      "Turcomenistão	",
      "Zimbábue",
      "Palestina",
    ],
    correct: 0,
    lvl: 2,
  },
  {
    title: "./flags/ma.png",
    alts: ["Sérvia", "Estônia", "Marrocos", "Grécia", "Coréia do Norte"],
    correct: 2,
    lvl: 1,
  },
  {
    title: "./flags/mq.png",
    alts: ["Suíça", "Martinica", "Hungria", "França", "Costa Rica"],
    correct: 1,
    lvl: 3,
  },
  {
    title: "./flags/mu.png",
    alts: ["Djibouti", "Comores", "Gabão", "Hong Kong", "Maurício"],
    correct: 4,
    lvl: 2,
  },
  {
    title: "./flags/mr.png",
    alts: ["Dominica", "Malauí", "Mauritânia", "Gana", "Djibouti"],
    correct: 2,
    lvl: 2,
  },
  {
    title: "./flags/yt.png",
    alts: ["Macau", "Sint Maarten", "Ilhas Cook", "Montserrat", "Mayotte"],
    correct: 4,
    lvl: 3,
  },
  {
    title: "./flags/mx.png",
    alts: ["Índia", "Irã", "Austrália", "México", "Alemanha"],
    correct: 3,
    lvl: 1,
  },
  {
    title: "./flags/mm.png",
    alts: ["Belize", "Mianmar", "Benin", "Malauí", "Paquistão"],
    correct: 1,
    lvl: 2,
  },
  {
    title: "./flags/mz.png",
    alts: ["Moçambique	", "Panamá", "Senegal", "Kosovo", "Sérvia"],
    correct: 0,
    lvl: 1,
  },
  {
    title: "./flags/md.png",
    alts: ["Grécia", "Equador", "Camarões", "Moldávia", "Butão"],
    correct: 3,
    lvl: 1,
  },
  {
    title: "./flags/mn.png",
    alts: [
      "Burundi",
      "Mongólia",
      "Cidade do Vaticano",
      "Bahamas",
      "República do Congo",
    ],
    correct: 1,
    lvl: 2,
  },
  {
    title: "./flags/me.png",
    alts: ["Estônia", "Hungria", "Montenegro	", "Nigéria", "Rússia"],
    correct: 2,
    lvl: 1,
  },
  {
    title: "./flags/ms.png",
    alts: [
      "Ilhas Turcas e Caicos",
      "Ilhas Marianas do Norte",
      "Guam",
      "Guadalupe",
      "Montserrat",
    ],
    correct: 4,
    lvl: 3,
  },
  {
    title: "./flags/na.png",
    alts: [
      "Iraque",
      "Papua Nova Guiné",
      "St. Kitts e Nevis",
      "Namíbia",
      "Sudão",
    ],
    correct: 3,
    lvl: 2,
  },
  {
    title: "./flags/nr.png",
    alts: [
      "Tajiquistão",
      "Sudão do Sul	",
      "Quênia",
      "Norte da Macedônia",
      "Nauru",
    ],
    correct: 4,
    lvl: 2,
  },
  {
    title: "./flags/np.png",
    alts: ["Nepal", "Tajiquistão", "Tanzânia", "Omã", "Maldivas"],
    correct: 0,
    lvl: 0,
  },
  {
    title: "./flags/ni.png",
    alts: ["El Salvador", "Grécia", "Nicarágua", "Kosovo", "Chile"],
    correct: 2,
    lvl: 1,
  },
  {
    title: "./flags/ne.png",
    alts: ["Grenada	", "Kiribati", "Kuwait", "Níger", "Maldivas"],
    correct: 3,
    lvl: 2,
  },
  {
    title: "./flags/ng.png",
    alts: ["Nigéria", "Canadá", "Belize", "Belarus", "Itália"],
    correct: 0,
    lvl: 1,
  },
  {
    title: "./flags/nu.png",
    alts: [
      "Ilhas Cayman",
      "Niue",
      "Jersey",
      "Ilhas Virgens (Reino Unido)",
      "Antártica",
    ],
    correct: 1,
    lvl: 3,
  },
  {
    title: "./flags/mk.png",
    alts: ["Bangladesh	", "Chade", "Norte da Macedônia", "Guatemala", "Iraque"],
    correct: 2,
  },
  {
    title: "./flags/no.png",
    alts: ["Índia", "Islândia", "Noruega", "Afeganistão", "Angola"],
    correct: 2,
    lvl: 1,
  },
  {
    title: "./flags/nc.png",
    alts: [
      "Ilha Norfolk",
      "Ilhas Marianas do Norte",
      "Gronelândia",
      "Antártica",
      "Nova Caledônia",
    ],
    correct: 4,
    lvl: 3,
  },
  {
    title: "./flags/nz.png",
    alts: ["Índia", "Alemanha", "Austrália", "Bulgária", "Nova Zelândia"],
    correct: 4,
    lvl: 1,
  },
  {
    title: "./flags/om.png",
    alts: ["Camboja", "Brunei", "Chade", "Mauritânia", "Omã"],
    correct: 4,
    lvl: 2,
  },
  {
    title: "./flags/nl.png",
    alts: ["Marrocos", "Turquia", "Países Baixos", "Uruguai", "Sérvia"],
    correct: 2,
    lvl: 1,
  },
  {
    title: "./flags/bq.png",
    alts: [
      "São Pedro e Miquelon",
      "Sint Maarten	",
      "Wallis e Futuna",
      "Países Baixos Caribenhos",
      "Ilha da Reunião",
    ],
    correct: 3,
    lvl: 3,
  },
  {
    title: "./flags/pw.png",
    alts: ["Palau", "Grenada", "Etiópia", "Gâmbia", "Burundi"],
    correct: 0,
    lvl: 2,
  },
  {
    title: "./flags/ps.png",
    alts: ["Palestina", "Fiji", "Grenada", "Chade", "Filipinas"],
    correct: 0,
    lvl: 2,
  },
  {
    title: "./flags/pa.png",
    alts: ["Eslovênia", "Rússia", "Eslováquia", "Panamá", "Espanha"],
    correct: 3,
    lvl: 1,
  },
  {
    title: "./flags/pg.png",
    alts: [
      "Burundi",
      "Cidade do Vaticano",
      "Micronésia",
      "Burkina Faso",
      "Papua Nova Guiné",
    ],
    correct: 4,
    lvl: 2,
  },
  {
    title: "./flags/pk.png",
    alts: ["Paquistão", "Sérvia", "Ucrânia", "Peru", "Montenegro"],
    correct: 0,
    lvl: 1,
  },
  {
    title: "./flags/py.png",
    alts: ["Senegal", "Paquistão", "Uruguai", "Lituânia", "Paraguai"],
    correct: 4,
    lvl: 1,
  },
  {
    title: "./flags/pe.png",
    alts: ["Lituânia", "Índia", "Peru", "Grécia", "Chile"],
    correct: 2,
    lvl: 1,
  },
  {
    title: "./flags/pf.png",
    alts: [
      "Ilha Norfolk",
      "Ilhas Åland",
      "Montserrat",
      "Polinésia Francesa",
      "Ilhas Pitcairn",
    ],
    correct: 3,
    lvl: 3,
  },
  {
    title: "./flags/pl.png",
    alts: ["Kosovo", "Japão", "China", "Polônia", "Singapura"],
    correct: 3,
    lvl: 1,
  },
  {
    title: "./flags/pr.png",
    alts: [
      "Porto Rico",
      "Montserrat",
      "Países Baixos Caribenhos",
      "São Pedro e Miquelon",
      "Samoa Americana",
    ],
    correct: 0,
    lvl: 3,
  },
  {
    title: "./flags/pt.png",
    alts: ["Porto Rico", "Peru", "Hungria", "Portugal", "Gana"],
    correct: 3,
    lvl: 1,
  },
  {
    title: "./flags/mc.png",
    alts: ["Camboja", "Grenada", "Chipre", "Chade", "Mônaco"],
    correct: 4,
    lvl: 2,
  },
  {
    title: "./flags/qa.png",
    alts: ["Armênia", "Qatar", "Cazaquistão	", "Argentina", "Hungria"],
    correct: 1,
    lvl: 1,
  },
  {
    title: "./flags/ke.png",
    alts: ["Maurício", "Kuwait", "Indonésia", "Camboja", "Quênia"],
    correct: 4,
    lvl: 2,
  },
  {
    title: "./flags/kg.png",
    alts: ["Mongólia", "Iêmen", "Quirguizistão", "Indonésia", "Liechtenstein	"],
    correct: 2,
    lvl: 2,
  },
  {
    title: "./flags/gb.png",
    alts: ["Paraguai", "Peru", "Reino Unido", "Nicarágua", "Vietnã"],
    correct: 2,
    lvl: 1,
  },
  {
    title: "./flags/cf.png",
    alts: ["República Centro-Africana", "Níger", "Omã", "Ruanda", "Tanzânia"],
    correct: 0,
    lvl: 2,
  },
  {
    title: "./flags/cd.png",
    alts: [
      "República do Congo",
      "São Vicente e as Granadinas	",
      "Serra Leoa",
      "República Democrática do Congo",
      "Sudão do Sul	",
    ],
    correct: 3,
    lvl: 2,
  },
  {
    title: "./flags/cg.png",
    alts: [
      "Seychelles",
      "Sudão do Sul	",
      "República do Congo",
      "República Democrática do Congo",
      "São Tomé e Príncipe",
    ],
    correct: 2,
    lvl: 2,
  },
  {
    title: "./flags/do.png",
    alts: ["Marrocos", "República Dominicana", "Romênia", "Noruega", "Panamá"],
    correct: 1,
    lvl: 1,
  },
  {
    title: "./flags/ro.png",
    alts: ["Panamá", "Palau", "Grécia", "Equador", "Romênia"],
    correct: 4,
    lvl: 1,
  },
  {
    title: "./flags/rw.png",
    alts: ["Níger", "Comores", "Ruanda", "Djibouti", "Dominica"],
    correct: 2,
    lvl: 2,
  },
  {
    title: "./flags/ru.png",
    alts: ["Nigéria", "Nicarágua", "Costa Rica", "França", "Rússia"],
    correct: 4,
    lvl: 1,
  },
  {
    title: "./flags/eh.png",
    alts: [
      "Ilha Norfolk",
      "Saara Ocidental",
      "Curaçao",
      "Ilhas Åland",
      "Ilhas Cocos",
    ],
    correct: 1,
    lvl: 3,
  },
  {
    title: "./flags/ws.png",
    alts: [
      "Ilha de Man",
      "Samoa",
      "Ilhas Malvinas	",
      "Ilhas Virgens dos Estados Unidos",
      "Sint Maarten",
    ],
    correct: 1,
    lvl: 3,
  },
  {
    title: "./flags/as.png",
    alts: [
      "Sint Maarten",
      "São Pedro e Miquelon",
      "Samoa Americana",
      "Samoa",
      "Países Baixos Caribenhos",
    ],
    correct: 2,
    lvl: 3,
  },
  {
    title: "./flags/sh.png",
    alts: [
      "Santa Helena",
      "Países Baixos Caribenhos",
      "Ilhas Faroe",
      "Ilhas Åland",
      "Ilha de Man",
    ],
    correct: 0,
    lvl: 3,
  },
  {
    title: "./flags/lc.png",
    alts: ["Hong Kong	", "Santa Lúcia", "Iêmen", "Grenada", "Eritreia"],
    correct: 1,
    lvl: 2,
  },
  {
    title: "./flags/bl.png",
    alts: [
      "Guam",
      "Gronelândia",
      "Gibraltar",
      "Ilha de Man",
      "Santo Bartolomeu",
    ],
    correct: 4,
    lvl: 3,
  },
  {
    title: "./flags/sm.png",
    alts: ["Guiana", "Lesotho	", "Guiana", "São Marino", "Guiné Equatorial"],
    correct: 3,
    lvl: 2,
  },

  {
    title: "./flags/pm.png",
    alts: [
      "Geórgia do Sul e as Ilhas Sandwich do Sul",
      "Ilhas Marianas do Norte",
      "Ilha da Reunião",
      "São Pedro e Miquelon",
      "Países Baixos Caribenhos",
    ],
    correct: 3,
    lvl: 3,
  },
  {
    title: "./flags/st.png",
    alts: [
      "São Tomé e Príncipe",
      "República Centro-Africana",
      "Quirguizistão",
      "Mongólia",
      "Maurício",
    ],
    correct: 0,
    lvl: 2,
  },
  {
    title: "./flags/vc.png",
    alts: [
      "República Democrática do Congo",
      "Quênia",
      "Mauritânia",
      "Iraque	",
      "São Vicente e as Granadinas",
    ],
    correct: 4,
    lvl: 2,
  },
  {
    title: "./flags/sn.png",
    alts: ["Irã", "Espanha", "Senegal", "Gana", "Chile"],
    correct: 2,
    lvl: 1,
  },
  {
    title: "./flags/sl.png",
    alts: ["Chade", "Serra Leoa", "Camboja", "Níger", "Cabo Verde	"],
    correct: 1,
    lvl: 2,
  },
  {
    title: "./flags/rs.png",
    alts: ["Sérvia", "Nicarágua", "Noruega", "Hungria", "Cuba"],
    correct: 0,
    lvl: 1,
  },
  {
    title: "./flags/sc.png",
    alts: [
      "Costa Rica",
      "Gabão",
      "Norte da Macedônia",
      "Seychelles",
      "Guiné-Bissau	",
    ],
    correct: 3,
    lvl: 2,
  },
  {
    title: "./flags/sx.png",
    alts: [
      "Curaçao",
      "Sint Maarten",
      "Ilha de Man	",
      "Ilhas Pitcairn",
      "Jersey",
    ],
    correct: 1,
    lvl: 3,
  },
  {
    title: "./flags/sy.png",
    alts: [
      "El Salvador",
      "Emirados Árabes Unidos	",
      "Grenada",
      "Síria",
      "Líbano",
    ],
    correct: 3,
    lvl: 2,
  },
  {
    title: "./flags/so.png",
    alts: ["Jordânia", "Liechtenstein	", "Somália", "Kuwait", "Quênia"],
    correct: 2,
    lvl: 2,
  },
  {
    title: "./flags/lk.png",
    alts: [
      "Jordânia",
      "República do Congo",
      "Quirguizistão	",
      "Líbia",
      "Sri Lanka",
    ],
    correct: 4,
    lvl: 2,
  },
  {
    title: "./flags/kn.png",
    alts: [
      "Eritreia",
      "Indonésia",
      "St. Kitts e Nevis",
      "São Marino",
      "República do Congo",
    ],
    correct: 2,
    lvl: 2,
  },
  {
    title: "./flags/sd.png",
    alts: [
      "Serra Leoa",
      "Sudão",
      "República Democrática do Congo",
      "Iraque",
      "Emirados Árabes Unidos	",
    ],
    correct: 1,
    lvl: 2,
  },
  {
    title: "./flags/ss.png",
    alts: [
      "Filipinas",
      "Sudão do Sul",
      "Emirados Árabes Unidos	",
      "Eswatini",
      "Gâmbia",
    ],
    correct: 1,
    lvl: 2,
  },
  {
    title: "./flags/se.png",
    alts: ["Espanha", "Estônia", "Eslováquia", "Suécia", "Finlândia"],
    correct: 3,
    lvl: 1,
  },
  {
    title: "./flags/ch.png",
    alts: ["Afeganistão", "França", "Suíça", "Finlândia", "Bolívia"],
    correct: 2,
    lvl: 1,
  },
  {
    title: "./flags/sr.png",
    alts: ["Suriname", "Azerbaijão", "Bahamas", "Guiné Equatorial", "Iêmen"],
    correct: 0,
    lvl: 2,
  },

  {
    title: "./flags/th.png",
    alts: ["Bolívia", "Tailândia", "Andorra", "Arábia Saudita", "Hungria"],
    correct: 1,
    lvl: 1,
  },
  {
    title: "./flags/tw.png",
    alts: ["Nepal", "Mongólia", "Moldávia", "Hong Kong", "Taiwan"],
    correct: 4,
    lvl: 2,
  },
  {
    title: "./flags/tj.png",
    alts: ["Moçambique	", "Iraque", "Guiné-Bissau", "Tajiquistão", "Paquistão"],
    correct: 3,
    lvl: 2,
  },
  {
    title: "./flags/tz.png",
    alts: ["Tuvalu", "Uganda", "Guiné-Bissau", "Tanzânia", "Zimbábue"],
    correct: 3,
    lvl: 2,
  },
  {
    title: "./flags/cz.png",
    alts: ["Peru", "Qatar", "Tcheca", "Hungria", "Paraguai"],
    correct: 2,
    lvl: 1,
  },
  {
    title: "./flags/io.png",
    alts: [
      "Ilhas Pitcairn	",
      "Território Britânico do Oceano Índico",
      "Territórios Franceses do Sul e Antártico",
      "Ilhas Virgens (Reino Unido)	",
      "Ilha de Natal	",
    ],
    correct: 1,
    lvl: 3,
  },
  {
    title: "./flags/tf.png",
    alts: [
      "Território Britânico do Oceano Índico	",
      "Ilhas Virgens dos Estados Unidos",
      "Ilhas Cocos",
      "Territórios Franceses do Sul e Antártico",
      "Ilhas Åland",
    ],
    correct: 3,
    lvl: 3,
  },
  {
    title: "./flags/tl.png",
    alts: ["Timor Leste", "Guiné", "Grenada", "Vanuatu", "Uzbequistão"],
    correct: 0,
    lvl: 2,
  },
  {
    title: "./flags/tg.png",
    alts: [
      "Guiné",
      "Emirados Árabes Unidos	",
      "Djibouti",
      "Togo",
      "Turcomenistão	",
    ],
    correct: 3,
    lvl: 2,
  },
  {
    title: "./flags/tk.png",
    alts: [
      "Tokelau",
      "Territórios Franceses do Sul e Antártico",
      "São Pedro e Miquelon",
      "Polinésia Francesa",
      "Macau",
    ],
    correct: 0,
    lvl: 3,
  },
  {
    title: "./flags/to.png",
    alts: ["Papua Nova Guiné", "Santa Lúcia", "Tonga", "Namíbia", "Tanzânia"],
    correct: 2,
    lvl: 2,
  },
  {
    title: "./flags/tt.png",
    alts: [
      "Suriname",
      "Trinidad e Tobago",
      "Guiné-Bissau",
      "Singapura",
      "Tanzânia",
    ],
    correct: 1,
    lvl: 2,
  },
  {
    title: "./flags/tn.png",
    alts: ["Coréia do Sul	", "Colômbia", "Butão", "Turquia", "Tunísia"],
    correct: 4,
    lvl: 1,
  },
  {
    title: "./flags/tm.png",
    alts: [
      "Tunísia",
      "República do Congo",
      "Turcomenistão",
      "Tailândia",
      "Sudão do Sul",
    ],
    correct: 2,
    lvl: 2,
  },
  {
    title: "./flags/tr.png",
    alts: ["Rússia", "Turquia", "Gana", "Tunísia", "Ucrânia"],
    correct: 1,
    lvl: 1,
  },
  {
    title: "./flags/tv.png",
    alts: ["Togo", "Uzbequistão", "Vanuatu", "Grenada", "Tuvalu"],
    correct: 4,
    lvl: 2,
  },
  {
    title: "./flags/ua.png",
    alts: ["Ucrânia", "Tunísia", "Irã", "Guiana", "Rússia"],
    correct: 0,
    lvl: 1,
  },
  {
    title: "./flags/ug.png",
    alts: ["Romênia", "Colômbia", "Egito", "Uganda", "Angola"],
    correct: 3,
    lvl: 1,
  },
  {
    title: "./flags/uy.png",
    alts: ["Alemanha", "Bolívia", "Jamaica", "Tcheca", "Uruguai"],
    correct: 4,
    lvl: 1,
  },
  {
    title: "./flags/uz.png",
    alts: ["Uzbequistão", "Tajiquistão", "Tanzânia", "Santa Lúcia", "Maurício"],
    correct: 0,
    lvl: 2,
  },
  {
    title: "./flags/vu.png",
    alts: ["Maldivas", "Vanuatu", "Madagascar", "Guiné Equatorial", "Tuvalu"],
    correct: 1,
    lvl: 2,
  },
  {
    title: "./flags/ve.png",
    alts: ["Vietnã", "Sérvia", "Israel", "Egito", "Venezuela"],
    correct: 4,
    lvl: 1,
  },
  {
    title: "./flags/vn.png",
    alts: ["Irã", "Vietnã", "Chipre", "Sérvia", "Arábia Saudita"],
    correct: 1,
    lvl: 1,
  },
  {
    title: "./flags/wf.png",
    alts: [
      "Anguila",
      "Ilha da Reunião",
      "Wallis e Futuna",
      "Ilha Norfolk",
      "Ilhas Turcas e Caicos",
    ],
    correct: 2,
    lvl: 3,
  },
  {
    title: "./flags/zm.png",
    alts: ["Zimbábue", "Vietnã", "Gâmbia", "Zâmbia", "Jordânia"],
    correct: 3,
    lvl: 2,
  },
  {
    title: "./flags/zw.png",
    alts: ["Zimbábue", "Iraque", "Zâmbia", "Kuwait", "Síria"],
    correct: 0,
    lvl: 2,
  },
  {
    title: "./flags/saba.png",
    alts: ["Saba", "Antártica", "Bermudas", "Ilhas Pitcairn", "Alderney"],
    correct: 0,
    lvl: 3,
  },
  {
    title: "./flags/Sld.png",
    alts: [
      "Saba",
      "Escócia",
      "Ilhas Pitcairn",
      "Ilhas Virgens dos Estados Unidos",
      "Inglaterra",
    ],
    correct: 1,
    lvl: 3,
  },
  {
    title: "./flags/Eng.png",
    alts: [
      "País de Gales",
      "Euskadi",
      "Gibraltar",
      "Inglaterra",
      "Ilha de Man",
    ],
    correct: 3,
    lvl: 3,
  },
  {
    title: "./flags/Wales.png",
    alts: ["Ilha de Natal", "País de Gales", "Ceuta", "Ilha Norfolk", "Jersey"],
    correct: 1,
    lvl: 3,
  },
  {
    title: "./flags/Mad.png",
    alts: [
      "Açores",
      "Catalunha",
      "Ilha da Madeira",
      "Macau",
      "Ilhas Marianas do Norte",
    ],
    correct: 2,
    lvl: 3,
  },
  {
    title: "./flags/Azo.png",
    alts: [
      "Ilhas Virgens (Reino Unido)",
      "Açores",
      "Territórios Franceses do Sul e Antártico",
      "Nova Caledônia",
      "Ilha da Madeira",
    ],
    correct: 1,
    lvl: 3,
  },
  {
    title: "./flags/Bas.png",
    alts: [
      "Basco",
      "Tokelau",
      "Catalunha",
      "Santa Helena",
      "lhas Pitcairn",
    ],
    correct: 0,
    lvl: 3,
  },
  {
    title: "./flags/Ald.png",
    alts: ["Geórgia", "Ilha de Natal", "Jersey", "Montserrat", "Alderney"],
    correct: 4,
    lvl: 3,
  },
  {
    title: "./flags/tri.png",
    alts: [
      "Anguila",
      "Montserrat",
      "Geórgia do Sul e as Ilhas Sandwich do Sul",
      "Gibraltar",
      "Tristão da Cunha",
    ],
    correct: 4,
    lvl: 3,
  },
  {
    title: "./flags/aut.png",
    alts: [
      "Saba",
      "Euskadi",
      "Ilhas Canárias",
      "Mayotte",
      "Ilhas Turcas e Caicos",
    ],
    correct: 2,
    lvl: 3,
  },
  {
    title: "./flags/ceu.png",
    alts: [
      "Ilhas Canárias",
      "Ceuta",
      "Guam",
      "Ilhas Marianas do Norte",
      "Polinésia Francesa",
    ],
    correct: 1,
    lvl: 3,
  },
];
